#
# Executes commands at the start of an interactive session.
#
# Authors:
#   David Mohl <me@dave.cx>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi


export LANG="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LC_MESSAGES="en_US.UTF-8"
export LC_MONETARY="en_US.UTF-8"
export LC_NUMERIC="en_US.UTF-8"
export LC_TIME="en_US.UTF-8"
export LC_ALL=

export PATH=/usr/local/bin:$PATH
export PATH="/opt/boxen/homebrew/opt/coreutils/libexec/gnubin:$PATH"
export PYTHONPATH="/opt/boxen/homebrew/opt/coreutils/libexec/gnubin:$PYTHONPATH"
export DEVELOPER_DIR="/Applications/Xcode6-Beta.app/Contents/Developer/"

alias activate="source venv/bin/activate"
alias serve='python -m SimpleHTTPServer 8000'
alias act='activate'

ggc () { git branch --remote | grep $1 | sed 's/origin\///g' | xargs git checkout  }
dep () {
	if [ $# -ne 0 ] 
	then
		hostname=staging:$1
	else
		hostname=staging
	fi

	fab $hostname force update && fab $hostname migrate && fab $hostname cutover 
}

# Source boxen
[ -f /opt/boxen/env.sh ] && source /opt/boxen/env.sh

# local / temporary overrides that don't need to go into this repository
[ -f ~/.localrc ] && source ~/.localrc

bindkey '^R' history-incremental-pattern-search-backward
bindkey '^[f' forward-word
bindkey '^[b' backward-word
