#
# Executes commands at the start of an interactive session.
#
# Authors:
#   David Mohl <me@dave.cx>
#


export LANG="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LC_MESSAGES="en_US.UTF-8"
export LC_MONETARY="en_US.UTF-8"
export LC_NUMERIC="en_US.UTF-8"
export LC_TIME="en_US.UTF-8"
export LC_ALL=

export PATH=/usr/local/bin:$PATH
export PATH=/opt/boxen/homebrew/bin/:$PATH
export PATH="/opt/boxen/homebrew/opt/coreutils/libexec/gnubin:$PATH"
export PYTHONPATH="/opt/boxen/homebrew/opt/coreutils/libexec/gnubin:$PYTHONPATH"
export DEVELOPER_DIR="/Applications/Xcode6-Beta.app/Contents/Developer/"

export VISUAL=vim
export EDITOR=vim

alias serve='python -m SimpleHTTPServer 8000'

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

activate() {
  [ -d venv ] && source venv/bin/activate
  [ -d ../venv ] && source ../venv/bin/activate
}

alias act='activate'

ggc () {
  git branch --remote | grep $1 | sed 's/origin\///g' | xargs git checkout
}

gsb () {
  git branch --all | grep $1 | sed 's/remotes\/origin\///g' | sed 's/\*/ /g'  | sort -u | uniq
}

# Deploy stuff
dep () {
  executionpath=$(pwd)
  [ -d venv ] && source venv/bin/activate
  [ -d ../venv ] && source ../venv/bin/activate
  fabfiledir=$(find . -name 'fabfile.py' | sed s/fabfile.py//g | sed s,\\./,,g)
  cd $fabfiledir

  if [ $# -ne 0 ]
  then
    hostname=staging:$1
  else
    hostname=staging
  fi

  if [ $# -eq 2 ]
  then
    fab $hostname force update && fab $hostname migrate && fab $hostname cutover
  else
    fab $hostname force update && fab $hostname cutover
  fi

  cd $executionpath
}

# SSH shortcuts. Every keystroke matters!
alias 'ystg'="ssh ystg"
alias 'stg'="ssh stg"

# Source boxen
[ -f /opt/boxen/env.sh ] && source /opt/boxen/env.sh

# local / temporary overrides that don't need to go into this repository
[ -f ~/.localrc ] && source ~/.localrc

bindkey '^E' end-of-line
bindkey '^A' beginning-of-line
bindkey '^R' history-incremental-pattern-search-backward
bindkey '^[[A' history-substring-search-down
bindkey '^[[B' history-substring-search-up

bindkey '^[f' forward-word
bindkey '^[b' backward-word
